
services:
  blipw_db:
    image: postgres:15-alpine
    
    container_name: blipw_postgres

    restart: always

    environment:
      POSTGRES_USER: blipw_admin
      POSTGRES_PASSWORD: adminpas_chebureki
      POSTGRES_DB: blipw_main


    ports:
      - "127.0.0.1:5432:5432"

    volumes:
      - blipw_postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql #заного читает init.sql при запуске. Закомментировать когда перестает быть нужным 

volumes:
  blipw_postgres_data: